name: todo_ecommerce
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  firebase_core: ^2.23.0
  cloud_firestore: ^4.13.2
  shimmer: ^3.0.0
  flutter_native_splash: ^2.3.6
  url_launcher: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^5.0.2
  lottie: ^2.7.0

dev_dependencies:
  hive_generator:
  build_runner:

  flutter_test:
    sdk: flutter



  flutter_lints: ^2.0.0
flutter_native_splash:
  color: "#000000"
  image: assets/images/todo_images.png



flutter:


  uses-material-design: true


  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/


  fonts:
     - family: Nunito-Regular
       fonts:
         - asset: assets/fonts/Nunito-Regular.ttf
     - family: OverlockSC
       fonts:
         - asset: assets/fonts/OverlockSC-Regular.ttf
