name: todo_ecommerce
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  firebase_core: ^2.23.0
  cloud_firestore: ^4.13.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/icons/


  fonts:
     - family: Nunito-Regular
       fonts:
         - asset: assets/fonts/Nunito-Regular.ttf
     - family: OverlockSC
       fonts:
         - asset: assets/fonts/OverlockSC-Regular.ttf
